[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/services"
  to = "https://services.publishing.umich.edu/"
  status = 301
  
 [[redirects]]
  from = "/publications/ee/"
  to = "https://services.publishing.umich.edu/publications/ee/"
  status = 301