[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/services"
  to = "https://services.publishing.umich.edu/"
  status = 301
  
 [[redirects]]
  from = "/publications/ee/"
  to = "https://services.publishing.umich.edu/publications/ee/"
  status = 301
 
 [[redirects]]
  from = "/publications/dice/"
  to = "https://services.publishing.umich.edu/publications/dice/"
  status = 301
  
 [[redirects]]
  from = "/publications/maize-books/possibility-of-practical-reason/"
  to = "https://services.publishing.umich.edu/publications/maize-books/possibility-of-practical-reason/"
  status = 301
 
 [[redirects]]
  from = "/news"
  to = "https://services.publishing.umich.edu/news"
  status = 301
  
 [[redirects]]
  from = "/directory"
  to = "/"
  status = 301
  
 [[redirects]]
  from = "/journals"
  to = "https://services.publishing.umich.edu/journals"
  status = 301

 [[redirects]]
  from = "/about"
  to = "/our-mission"
  status = 301

 [[redirects]]
  from = "/services/staff"
  to = "/our-mission"
  status = 301

 [[redirects]]
  from = "/2019/*"
  to = "https://services.publishing.umich.edu/2019/:splat"
  status = 301

[[redirects]]
  from = "/2018/*"
  to = "https://services.publishing.umich.edu/2018/:splat"
  status = 301

[[redirects]]
  from = "/2017/*"
  to = "https://services.publishing.umich.edu/2017/:splat"
  status = 301

[[redirects]]
  from = "/2016/*"
  to = "https://services.publishing.umich.edu/2016/:splat"
  status = 301

[[redirects]]
  from = "/2015/*"
  to = "https://services.publishing.umich.edu/2015/:splat"
  status = 301

[[redirects]]
  from = "/2014/*"
  to = "https://services.publishing.umich.edu/2014/:splat"
  status = 301

[[redirects]]
  from = "/2013/*"
  to = "https://services.publishing.umich.edu/2013/:splat"
  status = 301

[[redirects]]
  from = "/2012/*"
  to = "https://services.publishing.umich.edu/2012/:splat"
  status = 301

[[redirects]]
  from = "/2011/*"
  to = "https://services.publishing.umich.edu/2011/:splat"
  status = 301

[[redirects]]
  from = "/2010/*"
  to = "https://services.publishing.umich.edu/2010/:splat"
  status = 301
