backend:
  
  name: gitlab
  auth_type: implicit
  api_root: https://gitlab.umich.edu/api/v4
  base_url: https://gitlab.umich.edu
  auth_endpoint: oauth/authorize
  
  # Test settings. @todo comment out when deploying to prod
  branch: feature-page
  repo: kellerch/publishing-backup
  app_id: 40d8aa03d25b1c29bb69d7920ea01741830a426046fed6ff304344210737df6b
  
  # Production settings. @todo switch back to this when deploying to prod
  # branch: master
  # repo: michigan-publishing/publishing
  # app_id: 7df7120c922948a173c3ed23131e082a0b0b1307a8f01c6a12e60d1e49d86ec3
  
  # Local development settings
  # name: git-gateway
# local_backend: true

media_folder: static/assets
public_folder: /assets
collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: contact_info
        label: Contact info
        file: src/content/contact-info.md
        fields:
          - { name: type, label: Type, widget: hidden, default: contact_info }
          - { name: name, label: Name }
          - { name: address, label: Address }
          - { name: city, label: City }
          - { name: state, label: State }
          - { name: zip, label: Zip }
          - { name: email, label: Email }
          - { name: contact_link, label: "Contact us URL" }
          - name: social
            label: Social links
            label_singular: Social link
            widget: list
            fields:
              - { name: social_name, label: Social name }
              - { name: social_link, label: Social link }
  - name: landing_pages
    label: Landing pages
    editor:
      preview: false
    files:
      - name: homepage
        label: Homepage
        file: src/content/homepage.md
        fields:
          - { name: type, label: Name, widget: hidden, default: homepage }
          - name: hero_section
            label: Hero section
            widget: object
            fields:
              - { name: heading, label: Heading }
              - { name: text, label: Text, widget: markdown }
              - name: video
                label: Video
                widget: file
                default: ""
              - { name: video_description, label: Video description, widget: text, hint: Describe the video for users who cannot view it.}
              - { name: video_link_text, label: Video Link Text, default: "" }
              - { name: video_link, label: Video Link, default: "" }
          - name: highlight
            label: Highlight
            widget: object
            fields:
              - { name: heading, label: Heading }
              - { name: link_text, label: Link text }
              - { name: link_url, label: Link URL }
              - name: image
                label: Image
                widget: object
                fields:
                  - { name: file, label: File, widget: image }
                  - { name: alt, label: Alt text }
          - {
            name: profile,
            label: Featured profile,
            widget: relation,
            collection: profiles,
            searchFields: [title],
            valueField: title,
          }
          - {
            name: stories,
            label: Featured stories,
            widget: relation,
            collection: stories,
            searchFields: [title],
            valueField: title,
            multiple: true,
          }
          - name: infographics
            label: Infographics section
            widget: object
            fields:
              - {name: heading, label: Heading}
              - name: infographics
                label: Infographics
                label_singular: Infographic
                widget: list
                fields:
                  - { name: large_text, label: Large text }
                  - { name: small_text, label: Small text }

  - name: pages
    label: Pages
    label_singular: Page
    editor:
      preview: false
    folder: src/content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }
      - { name: type, label: Type, widget: hidden, default: page }

  - name: books
    label: Books
    label_singular: Book
    create: true
    editor:
      preview: false
    folder: src/content/books
    fields:
      - { name: title, label: Title }
      - { name: link, label: Link, required: false, default: "" }
      - { name: author, label: Author }
      - name: image
        label: Image
        widget: object
        fields:
          - { name: file, label: File, widget: image }
          - { name: alt, label: Alt text }
      - { name: description, label: Description, widget: text }
      - { name: type, label: Type, widget: hidden, default: book }

  - name: features
    label: Features
    label_singular: Feature
    create: true
    folder: src/content/features
    editor:
      preview: false
    fields:
      - { name: type, label: Type, widget: hidden, default: feature }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: path, label: Path }
      - name: hero
        label: Hero section
        widget: object
        required: false
        fields:
          - { name: text, label: Text, widget: text, required: false, default: "" }
          - { name: feature_hero_image, label: Image, widget: image, required: false, default: "" }
      - name: feature_image
        label: Image
        widget: object
        fields:
          - { name: file, label: File, widget: image }
          - { name: alt, label: Alt text }
      - { name: body, label: Body, widget: markdown }

      - name: sections
        label: Sections
        widget: list
        fields:
          - label: Heading
            name: heading
          - label: Subheading
            name: subheading
          - label: Content
            name: content
            widget: list
            types:
              - label: Quote slider
                name: quote_slider
                widget: object
                fields:
                  - {
                    name: book,
                    label: Book,
                    widget: relation,
                    collection: books,
                    searchFields: [title],
                    valueField: title,
                    default: [""]
                  }
                  - label: Quote
                    name: quote
                    widget: object
                    fields:
                      - label: Quote
                        name: quote
                        widget: text
                      - label: Name
                        name: name
                      - label: Title
                        name: title
                  - label: Slides
                    name: slides
                    widget: list
                    fields:
                      - label: Image
                        name: image
                        widget: image
                        required: false
                        default: ""
                      - label: Image Alt
                        name: image_alt
                        required: false
                        default: ""
                      - label: Title
                        name: title
                        required: false
                        default: ""
                      - label: Text
                        name: text
                        widget: text
                        required: false

              - label: Call to Action
                name: cta
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Image Alt
                    name: image_alt
                    required: false
                  - label: Heading
                    name: heading
                  - label: Text
                    name: text
                    widget: text
                  - label: Button text
                    name: button_text
                  - label: Button URL
                    name: button_link

              - label: Spacer
                name: spacer
                widget: object
                fields:
                  - label: Spacer
                    name: spacer
                    default: Spacer
                    hint: Adds border seperator to content. Text entered in this field is for admin purposes only and will not display on the site.

              - label: Podcast
                name: podcast
                widget: object
                fields:
                  - label: Embed code
                    name: embed_code
                    widget: text

              - label: Profile
                name: profile
                widget: object
                fields:
                  - label: Profile
                    name: profile
                    widget: relation
                    collection: profiles
                    searchFields: [title]
                    valueField: title

              - label: YouTube
                name: youtube
                widget: object
                fields:
                  - label: Video ID
                    name: id

              - label: Highlight box
                name: highlight
                widget: object
                fields:
                  - label: Text
                    name: text
                    widget: markdown

              - label: Image
                name: image
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Image Alt
                    name: image_alt
                  - label: Caption
                    name: caption
                    required: false
                  - label: Credit
                    name: credit
                    required: false

      - {
        name: related_stories,
        label: Related Stores,
        widget: relation,
        collection: stories,
        searchFields: [title],
        valueField: title,
        multiple: true,
        required: false,
        default: [""],
      }

  - name: stories
    label: Stories
    label_singular: Story
    create: true
    folder: src/content/stories
    fields:
      - { name: published, label: Published, widget: boolean, default: true }
      - {
          name: categories,
          label: Categories,
          widget: relation,
          collection: categories,
          searchFields: [title],
          valueField: title,
          multiple: true,
        }
      - { name: title, label: Title }
      - { name: path, label: Path, default: /stories-of-impact/story-name }
      - name: hero
        label: Hero section
        widget: object
        required: false
        fields:
          - { name: text, label: Text, widget: text, required: false, default: "" }
          - { name: story_hero_image, label: Image, widget: image, required: false, default: "" }
      - name: story_image
        label: Image
        widget: object
        fields:
          - { name: file, label: File, widget: image }
          - { name: alt, label: Alt text }
          - { name: caption, label: Caption, required: false, default: "" }
          - { name: credit, label: Credit, required: false, default: "" }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author, required: false }
      - { name: date, label: Date, widget: date }
      - name: highlight_box
        label: Highlight box
        widget: object
        required: false
        fields:
          - { name: text, label: Text, widget: markdown, required: false, default: "" }
      - {
          name: books,
          label: Books,
          widget: relation,
          collection: books,
          searchFields: [title],
          valueField: title,
          multiple: true,
          required: false,
          default: [""]
        }
      - {
          name: profiles,
          label: Profiles,
          widget: relation,
          collection: profiles,
          searchFields: [title],
          valueField: title,
          multiple: true,
          required: false,
          default: [""],
        }
      - {
          name: related_stories,
          label: Related Stores,
          widget: relation,
          collection: stories,
          searchFields: [title],
          valueField: title,
          multiple: true,
          required: false,
          default: [""],
        }
      - { name: type, label: Type, widget: hidden, default: story }

  - name: profiles
    label: Profiles
    label_singular: Profile
    create: true
    folder: src/content/profiles
    editor:
      preview: false
    fields:
      - { name: title, label: Name }
      - { name: job_title, label: Title }
      - { name: faculty_image, label: Image, widget: image }
      - name: quotes
        label: Quotes
        label_singular: Quote
        widget: list
        required: false
        fields:
          - { name: quote, label: Quote, widget: text }
      - { name: bio, label: Bio, widget: text, default: "", required: false }
      - { name: type, label: Type, widget: hidden, default: profile}

  - name: categories
    label: Categories
    label_singular: Category
    create: true
    folder: src/content/categories
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
