backend:
  name: gitlab
  repo: umichcreative/publishing
  auth_type: implicit
  app_id: 1425f6591e2190ac420513b6d866409b6d23f6ad75100233a0ff9e466df0198a
media_folder: static/assets
public_folder: assets
collections:
  - name: settings
    label: Settings
    files:
      - name: homepage
        label: Homepage
        editor:
          preview: false
        file: src/content/homepage.md
        fields:
          - { name: type, label: Name, widget: hidden, default: homepage }
          - name: hero_section
            label: Hero section
            widget: object
            fields:
              - { name: heading, label: Heading }
              - { name: text, label: Text, widget: markdown }
              - name: image
                label: Image
                widget: object
                fields:
                  - { name: file, label: File, widget: image }
                  - { name: alt, label: Alt text }

  - name: pages
    label: Pages
    label_singular: Page
    editor:
      preview: false
    folder: src/content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: path, label: Path }
      - { name: type, label: Type, widget: hidden, default: page }

  - name: books
    label: Books
    label_singular: Book
    create: true
    editor:
      preview: false
    folder: src/content/books
    fields:
      - { name: title, label: Title }
      - { name: author, label: Author }
      - name: image
        label: Image
        widget: object
        fields:
          - { name: file, label: File, widget: image }
          - { name: alt, label: Alt text }
      - { name: description, label: Description, widget: text }

  - name: stories
    label: Stories
    label_singular: Story
    create: true
    editor:
      preview: false
    folder: src/content/stories
    fields:
      - { name: title, label: Title }
      - name: hero
        label: Hero section
        widget: object
        fields:
          - { name: text, label: Text, widget: text, required: false }
          - { name: image, label: Image, widget: image, required: false }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: date }
      - {
          name: categories,
          label: Categories,
          widget: relation,
          collection: categories,
          searchFields: [title],
          valueField: title,
          multiple: true,
        }
      - name: image
        label: Image
        widget: object
        fields:
          - { name: file, label: File, widget: image }
          - { name: alt, label: Alt text }
          - { name: caption, label: Caption, required: false }
          - { name: credit, label: Credit, required: false }
      - {
          name: profiles,
          label: Profiles,
          widget: relation,
          collection: profiles,
          searchFields: [title],
          valueField: title,
          multiple: true,
          required: false,
        }
      - {
          name: project_partners,
          label: Project Partners,
          widget: markdown,
          required: false,
        }
      - {
          name: related_stories,
          label: Related Stores,
          widget: relation,
          collection: stories,
          searchFields: [title],
          valueField: title,
          multiple: true,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - { name: path, label: Path, default: /stories/ }
      - { name: type, label: Type, widget: hidden, default: story }

  - name: profiles
    label: Profiles
    label_singular: Profile
    create: true
    folder: src/content/profiles
    editor:
      preview: false
    fields:
      - { name: title, label: Name }
      - { name: job_title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: quote, label: Quote, widget: text }

  - name: categories
    label: Categories
    label_singular: Category
    create: true
    folder: src/content/categories
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
